var roleNumbers = [
  491, 494, 507, 509, 510, 516,
  521, 525, 527, 530, 532, 535,
  540, 543, 545, 548, 551, 553,
  554, 555, 556, 558, 564, 565,
  567, 568, 569, 570, 572, 573,
  574, 575, 578, 579, 581, 587,
  588, 589, 590, 592, 593, 594,
  595, 596, 597, 599, 600, 601,
  602, 603, 604, 605, 606, 607,
  609, 611, 612, 613, 614, 615,
  616, 617, 618, 619, 620, 622,
  623, 624, 625, 626, 627, 628,
  629, 630, 631, 632, 633, 634,
  635, 637, 638, 639, 640, 641,
  642
];
var names = [
  "kaylee",
  "alexandria",
  "julie",
  "joshua",
  "vanessa",
  "molly",
  "amanda",
  "julian",
  "jessica",
  "jessica",
  "david",
  "gregory",
  "nicholas",
  "emily",
  "gabriela",
  "matteo",
  "michael",
  "marissa",
  "kenny",
  "katelyn",
  "francis",
  "carter",
  "parth",
  "josh",
  "jonathan",
  "caroline",
  "danny",
  "shahbaz",
  "alia",
  "malik",
  "chris",
  "david",
  "rayane",
  "kristen",
  "kayla",
  "amy",
  "cyan",
  "devin",
  "mark",
  "karan",
  "ariana",
  "aubrey",
  "reuben",
  "ethan",
  "daniel",
  "mark",
  "arpit",
  "valentino",
  "alex",
  "luis",
  "corey",
  "david",
  "quinten",
  "andrea",
  "brooke",
  "thomas",
  "ashnee",
  "tristan",
  "nicholas",
  "samuel",
  "emily",
  "whitney",
  "klaudja",
  "royce",
  "alexander",
  "andrew",
  "sean",
  "kirsten",
  "sabrina",
  "katherine",
  "ryan",
  "sara",
  "aaron",
  "kendall",
  "alyssa",
  "dean",
  "brendan",
  "andrea",
  "logan",
  "thapthim",
  "max",
  "jessica",
  "jose",
  "farah",
  "meredith"
];
var majors = [
    "mechanical",
    "mech aero",
    "electrical",
    "electrical",
    "mech aero",
    "mechanical",
    "mechanical",
    "electrical",
    "electrical",
    "information systems and operations management",
    "chemical",
    "civil",
    "electrical",
    "civil",
    "mechanical",
    "mechanical",
    "mechanical",
    "mechanical",
    "electrical",
    "mechanical",
    "mechanical",
    "mechanical",
    "mech aero",
    "mechanical",
    "materials",
    "computer science",
    "chemical",
    "environmental",
    "information systems",
    "electrical",
    "electrical",
    "mechanical",
    "mechanical",
    "chemical",
    "nuclear",
    "mechanical",
    "computer science",
    "industrial and systems",
    "environmental",
    "computer science",
    "industrial and systems",
    "industrial and systems",
    "mech aero",
    "mechanical",
    "electrical",
    "mechanical",
    "mechanical",
    "computer science",
    "computer science",
    "chemical",
    "animal sciences and biology",
    "mechanical",
    "civil",
    "aerospace",
    "mechanical",
    "mech aero",
    "materials",
    "electrical",
    "electrical",
    "biological",
    "mechanical",
    "civil",
    "environmental",
    "environmental",
    "computer science",
    "industrial",
    "mechanical",
    "electrical",
    "mechanical",
    "electrical",
    "environmental",
    "mechanical",
    "mechanical",
    "mechanical",
    "biological",
    "chemical",
    "chemical",
    "civil",
    "mechanical",
    "biomedical",
    "computer science",
    "materials",
    "computer engineering",
    "biological",
    "mechanical"
];
var hometowns = [
    "Tallahassee",
    "Melbourne",
    "Orlando",
    "Parrish",
    "Miami",
    "Ocoee",
    "Wellington",
    "Miami",
    "Dhahran, Saudi Arabia",
    "Hollywood",
    "New Port Rickey",
    "Loxahatchee",
    "Jacksonville",
    "Winter Park",
    "Palm Beach Gardens",
    "Safety Harbor",
    "Sarasota",
    "Orlando",
    "Miami",
    "Navarre",
    "Miami",
    "Tampa",
    "Coral Springs",
    "Boca Raton",
    "Bonita Springs",
    "Palm Harbor",
    "Jacksonville",
    "Orlando",
    "Winter Springs",
    "Port St. Lucie",
    "Jacksonville Beach",
    "Miami",
    "Shrewsbury, Massachusetts",
    "Niceville",
    "Pembroke Pines",
    "Orlando",
    "Tampa",
    "Sarasota",
    "Environmental",
    "Mississuaga, Canada",
    "Tampa",
    "North Palm Beach",
    "Hollywood",
    "Boca Raton",
    "Windermere",
    "Jacksonville",
    "Fleming Island",
    "Jupiter",
    "Deerfield Beach",
    "Caracas, Venezuela",
    "Niceville",
    "Weston",
    "West Palm Beach",
    "Miami",
    "Wellington",
    "Saint-Maur des Fosses",
    "Ponte Vedra Beach",
    "Manalapan, New Jersey",
    "Coral Springs",
    "Valrico",
    "Tampa",
    "Gainesville",
    "Jacksonville",
    "Jacksonville",
    "Port St. Lucie",
    "Boca Raton",
    "Manchester, New Hampshire",
    "Barrington, Rhode Island",
    "Hollywood",
    "Lutz",
    "Parkland",
    "Miami",
    "Elko, Nevada",
    "Chicago, Illinois",
    "Weston",
    "Parkland",
    "Bridgewater, New Jersey",
    "Tallahassee",
    "Gainesville",
    "Fort Walton Beach",
    "Miami",
    "Jacksonville",
    "Guayaquil, Ecuador",
    "Fort Myers",
    "Niceville"
];
var prevName = "";
var score = 0;
var step = 0;

function start(){
    document.getElementById('theImage').src = "img/" + roleNumbers[step] + ".jpg";
    document.getElementById('score2').textContent = "Score: " + score + ", Role Number: " + roleNumbers[step];
}

function check(){
    document.getElementById("name").focus();
    if(document.getElementById("name").value.toLowerCase() == names[step] &&
      document.getElementById("major").value.toLowerCase() == majors[step] &&
      document.getElementById("hometown").value.toLowerCase() == hometowns[step].toLowerCase()){
        score++;
    }
    document.getElementById("name").value = "";
    document.getElementById("major").value = "";
    document.getElementById("hometown").value = "";
    step++;
    document.getElementById('theImage').src = "img/" + roleNumbers[step] + ".jpg";
    document.getElementById('score2').textContent = "Score: " + score + ", Role Number: " + roleNumbers[step];
}

/*function start(){
  document.getElementById('theImage').src = "img/" + roleNumber + ".jpg";
  document.getElementById("score").textContent = "Score: " + score + ", Role Number: " + roleNumber + ", Members checked: " + (usedNames.length);
  //document.getElementById("score2").innerHTML = usedNames.toString();
}

function check(){
  step++;
  prevName = roleName;
  if(document.getElementById("textBox").value == roleName){
    score += 1;
    document.getElementById("score2").textContent = "";
  }else{
    document.getElementById("score2").textContent = "INCORRECT: That was " + prevName + ".";
  }
  document.getElementById("score").textContent = "Score: " + score + ", Role Number: " + roleNumber + ", Members checked: " + (usedNames.length);
  //document.getElementById("score2").innerHTML = usedNames.toString();
  document.getElementById("textBox").value = "";
  document.getElementById('theImage').src = "img/" + roleNumber + ".jpg";
}
*/